configs:
  secret:
    argocdServerAdminPassword: $2a$10$m3eTlEdRen0nS86c5Zph5u/bDFQMcWZYdG3NVdiyaACCqoxLJaz16
    argocdServerAdminPasswordMtime: 2021-11-08T15:04:05Z
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: contour
    hostname: argocd.52.55.169.154.nip.io
  extraArgs:
  - --insecure
