apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm/kagent
    chart: kagent
    targetRevision: "*"
    helm:
      parameters:
      - name: providers.anthropic.apiKey
        value: "${ANTHROPIC_API_KEY}"
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true